### ISSUE TITLE
Use the most recent score or the highest score on workout offerings

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#100]
Add a boolean field to WorkoutOffering that defaults to ```true``` for using the most recent score, and ```false``` for the highest score. Make other changes to the logic when recording scores to account for this.

**Comment by ayaankazerouni** [comment]
(see commit 354e31d) New attempts get saved to the database regardless of policy. However, they get associated with the workout score through the ```active_score``` association if:
* the workout_offering has the most_recent flag set to ```true```, OR
* the new attempt's score is ```>=``` the current score on the workout_offering

Each exercise thumbnail still displays the latest attempt's score. We should talk about whether we want to leave this like this. 
**Argument for**: The practice page shows the feedback and the code from the most recent attempt, so the displayed score should correspond to those.
**Argument against**: The displayed exercise scores won't add up to the current score shown for the workout as a whole.

Leaving this open for now.

**Comment by s-edwards** [comment]
You accidentally committed the changes to the resources config.rb that removed security enforcement.  The change may be necessary for local testing on your dev machine, but don't check it in or it might accidentally get merged.

**Comment by s-edwards** [comment]
The code as-is isn't quite right.  First, note that this looks at the workout score, not the attempt score, in order to determine whether the new attempt should become the active scored attempt.  The determination should be made by comparing the current attempt's (timestamp or score) against the current active scored attempt's (timestamp or score), not the workout's score.  Since the workout's score is stored in rounded form, the calculation now (which compares an unrounded new total against a rounded stored total) can be inaccurate in some cases.  Also, since the intent is to compare the current attempt against the active scored attempt, it is better to make the calculation follow the intent, instead of working off the cumulative workout score.

On other question: Exercise thumbnails should always show the active scored attempt's score, no question.

The issue is what shows on the practice page.  It makes sense that the practice page shows the code + feedback from the most recent attempt, so the student can continue working.  It also makes sense that the code + feedback shown on the practice page come from the same attempt.  The question is that, when highest score is chosen over most recent, there's no obvious way for students to see/access/revert to the highest-scoring attempt that is currently determining their score.  This, of course, only makes sense if they can see their scores/feedback in detail.  This all makes me reconsider whether this should be an option on the workout offering (like I initially thought) or on the workout policy.  I'm still thinking this idea of keeping the highest score only makes sense in time-limited/feedback-limited test or quiz situations.

**Comment by ayaankazerouni** [comment]
> You accidentally committed the changes to the resources config.rb that removed security enforcement.

Sorry about that, I've reverted it.

I've addressed the concerns that you brought up -- comparisons happen before calculating the workout_score, and they happen between the current attempt and last scored attempt (unrounded).

> I'm still thinking this idea of keeping the highest score only makes sense in time-limited/feedback-limited test or quiz situations.

Ok, so do you want to gather feedback from instructors before proceeding?

**Comment by ayaankazerouni** [comment]
Closing this, since there's been no talk and the feature is implemented and merged into production. Can be reopened if this needs to be revisited.

**Comment by s-edwards** [comment]
Did it make it into the workout edit form also?  I  know it is implemented internally for new workouts.  However, if the choice is changed on the fly via the edit form, code to re-score existing workout scores isn't in place yet, AFAIK.

**Comment by ayaankazerouni** [comment]
Correct, this is incomplete in that existing attempts are not rescored when the setting is changed using the form. Only future attempts are affected (though even then, they are evaluated against the current active_score, so it still needs work). I didn't think of this.

**Comment by ayaankazerouni** [comment]
In the model method WorkoutScore#record_attempt, I wanted to re-use the code to recalculate the workout_score. This happens after the active_score_ids have been set appropriately, so it's just a simple summing up.

However, moving that code to an instance method wouldn't work unless I moved the corresponding call to *outside* the transaction block in record_attempt. See https://github.com/web-cat/code-workout/blob/de6d56de2b34d471b4a4f737947b60a3479aad9d/app/models/workout_score.rb#L247

Leaving open until I get some feedback on the implications of this and/or ideas on how to get around it.

**Comment by s-edwards** [comment]
First, updating/recalculating the workout score must **always** be done inside a transaction on the WorkoutScore object.  **Always**.  It should never, ever be done outside a transaction, or a race condition will be introduced.  This basically means moving that code to a new instance method will require that new instance method's body to be wrapped in a self.transaction block, just like the record_attempt method is (which is also an instance method).

Further, any code that calls such a method should either (a) not make any other modifications to the WorkoutScore object, or (b) needs to itself also be wrapped in a transaction on that object.  Right now, the only code that is "safe" to change WorkoutScore objects outside of transactions is the part of the code where the WorkoutScore is created and first stored, since at that point there cannot be other threads accessing it.

When you say introducing such a method would require "mov[ing] the corresponding call to _outside_ the transaction block in record_attempt", I don't know what you mean, or why you think that is required?  The call should definitely remain _inside_ the transaction block or the block will no longer represent an atomic action.  Effectively, using transaction blocks both in the calling method and inside the called method creates nested transactions ... but since these would be transactions on the same object, there's no danger of non-monotonic locking and there shouldn't be any worries that come with more complicated nested transaction situations.

Which raises another issue--I thought the transaction instance method acquired a row lock on the instance.  But it does not.  This is the source of the update issues that we saw recently.  They are significantly reduced, but not eliminated.  We need to add lock! behavior to the transactions to protect against concurrent modifications between parallel processes under deployment.

**Comment by s-edwards** [comment]
It looks like we should replace some_object.transaction with some_object.with_lock to use lock-based transactions.  Not sure how I didn't find that when first setting up the transactions.

**Comment by ayaankazerouni** [comment]
> This basically means moving that code to a new instance method will require that new instance method's body to be wrapped in a self.transaction block, just like the record_attempt method is (which is also an instance method).

Ok.

> When you say introducing such a method would require "mov[ing] the corresponding call to outside the transaction block in record_attempt", I don't know what you mean, or why you think that is required?

The effects of the call were not reflected in the DB when the call was inside the transaction block. For example -- regardless of the scoring policy (most recent or highest scoring attempt), the attempt would get recorded, but the active_score would not be updated. The active_score would only be updated if the call to the instance method was made outside the transaction block, or if the code in question was not extracted to an instance method in the first place.

Now it seems as if using a transaction (or with_lock, rather) block in the instance method would fix the behaviour described above.

**Comment by ayaankazerouni** [comment]
I don't think the `update_lti` helper method needs its own `with_lock` block, since it doesn't update the WorkoutScore, it just calculates a total and sends it to the LMS. If this understanding is correct, then we can close this issue (and staging is good to go).

**Comment by ayaankazerouni** [comment]
Closing after discussion with Dr. Edwards
