### ISSUE TITLE
Hidden score info leaks on grades tab of course home page

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#101]
If a workout's policy indicates students cannot see feedback, the score is hidden in the workout thumbnail.  However, full scores are always visible on the grades tab of the course home page.

We should change the grades tab on the course home page to hide scores (or "blur" scores, as done in the thumbnails) for workouts where score feedback is not currently visible to the student.  The blurring should only be for students--it is OK for this information to be visible to users managing the course or with admin access.

**Comment by ayaankazerouni** [comment]
I'm confused -- this is already implemented and working. The ```workout_score.show_feedback?``` method checks the two policy attributes related to feedback. In exercises/practice.html.haml, if ```workout_score.show_feedback?``` returns ```false```, then the score is displayed as "-/-". 

From a UI standpoint, this is not great and I can fix it, but I just want to make sure I understand what this issue is about.

**Comment by ayaankazerouni** [comment]
Closing after discussion.
