### ISSUE TITLE
More sophisticated rights around exercises, workouts, courses.

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#108]
Similar to ```WorkoutPolicy```, need a policy model that controls permissions around an ```ExerciseCollection```. This is separate from but related to another required model for an exercise's ```License``` (Apache, Creative Commons, etc).

Some initial permissions for ```LicensePolicy```:
* Is it publicly available?
* Is it fork-able? Who can fork it?

Exercise collections could be tied to courses, so users can get permissions for sets of exercises. But they can also be tied to other entities, for example OpenDSA exercises would be in a group of their own.

We might end up with groups of users that collectively have permissions over courses, workouts and exercises. 

# Relationships

* ```UserGroup``` M <--------> M ```User```
* ```Course``` 0 <--------> 1 ```UserGroup```
* ```ExerciseCollection``` 1 <--------> M ```Exercise``` (every user implicitly has a private group that they are the sole member of. Exercises might initially be part of this private group, until the user is ready to move it to a user group).
* ```ExerciseCollection``` M <--------> 1 ```License```
* ```ExerciseCollection``` 1 <--------> 1 ```UserGroup```
* ```LicensePolicy``` 1 <--------> M ```License```

**Comment by ayaankazerouni** [comment]
Regarding the ```ExerciseCollection``` - ```UserGroup``` relationship: should there also be a ```ExerciseCollection```-```User``` relationship, to make the 'private' grouping work? So ```ExerciseCollection``` would have two foreign keys, **only one of which would be ```not nil``` at any given time**.

**Comment by s-edwards** [comment]
There are two different ways of implementing a per-user "private" group.  One is as you suggest (i.e., don't implement those as regular UserGroup objects, and instead use a separate relation), and the other is to actually use UserGroup objects with a single member. Both approaches work, but there is a tradeoff--using the separate relation avoids creating a massive number of single-member user groups, but makes the access/rights logic more complicated. I think using a separate relation as you suggest is fine, as long as you make sure that the access rights enforcement works correctly (and it also means methods for this can't all be centralized in the user group class, since private groups won't use that class).

**Comment by ayaankazerouni** [comment]
@s-edwards  Did you mean to close the issue? This is far from finished, right?

Also -- I was thinking that the `edit` permission would check the old abilities (i.e., admin and/or exercise_owner) as usual, and if neither of these are true, would allow access if:
* The ``Exercise`` is part of an ``ExerciseCollection`` that points to a ``UserGroup``` containing our user
* The ``Exercise`` is part of an ``ExerciseCollection`` that points to our user

I *think* these should be straightforward to implement.

**Comment by s-edwards** [comment]
Oops--you're right, I pressed the wrong button to post my comment.

**Comment by ayaankazerouni** [comment]
I've updated Exercise permissions to be decided based off the exercise itself and the `ExerciseCollection` it belongs to, if any (and its associated `UserGroup` and `License`)

At our meeting last week, we talked about adding a `UserGroup-CourseOffering` association. We're already controlling permissions based on `CourseEnrollment`, so I'm unsure about the purpose of this relation.

**Comment by ayaankazerouni** [comment]
Closing for now.
