### ISSUE TITLE
TestCases expect non-blank inputs

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#165]
The `TestCase` model has a not-null property on the `input` field. This disallows test cases that have no inputs associated with them. These are possible for problems that are simply giving practice with printing or string concatenation etc.

Proposed fix:
* Change `TestCase` to allow null values for the `input` field
* Change the [`TestCase.to_code`](https://github.com/web-cat/code-workout/blob/4cda81573c8d069bc3bde94aae6a327fad3b6282/app/models/test_case.rb#L272) method to deal with null inputs appropriately

**Comment by s-edwards** [comment]
The input value should be an empty string instead of null in this case, I think ... either that, or we can remove the null constraint and treat null the same as the empty string. However, an "empty" input value should be supported (it's just that right now it is only supported as an empty string, which the code doesn't comply with when the CSV parser parses an empty cell value and returns null).

**Comment by s-edwards** [comment]
It would probably be an easier solution to represent "empty" cell values as empty strings instead of nulls, in terms of requiring the least code changes?

**Comment by ayaankazerouni** [comment]
Fixed, but without a migration to change the constraint. Changed the validation of test case inputs from `presence: true` to `allow_nil: false, length: { minimum: 0 }` as per rails/rails#7180
