### ISSUE TITLE
Privacy statement and terms of use

### ISSUE THREAD

**Issue by axel1200** [web-cat/code-workout#167]
Don't you need a privacy statement and terms of use. You are storing personal data. At least if others should be able to use you hosted instance. Not sure if that is the goal.

**Comment by axel1200** [comment]
Also is there a way to get the question database of the hosted code work out instance. Like the example.yaml files. I mean for many other institutions hosting their own instance is the only way, cause even if Code Workout had a proper Privacy Statement, storing student data in the US might be problematic.

**Comment by s-edwards** [comment]
I agree that laws in different countries makes storing student data on US servers problematic in some ways, and that running your own server may be the only answer for other institutions (for a variety of reasons).

At present, there is no public version of the question database, and there won't be, at least in the simplistic form of "here's all the questions". The problem is that questions come from different sources and are under different licensing terms. They range from completely free/open questions, to completely private questions, to copyrighted questions associated with a specific textbook (you can use it as long as you're using the textbook, but there's no legal way to "publish" those in a public database people can copy from, for example), and on and on.

We've been in discussions on the best way to put up a question database. We're probably going to end up using a separate database for each body of questions that are controlled by a different copyright owner or license, and just use private git repositories to manage this. So we're in the process of doing that, yes.

In the meantime, if you're at another school and want to set up your own server, please work with us directly so we can help you through the process. We can arrange a way to share the exercises we have, even if doing it through a single publicly available database is not feasible. There are a number of things in the data model (and under development) that are specifically set up to allow tracking license restrictions on exercises and allowing instructors to opt-in to access-controlled collections they are eligible for (such as textbook-specific question banks), and those features would automatically be used on another deployment at another school. So yeah, we can work something out with schools that wish to partner for exercise access and/or deployment advice, certainly.

**Comment by s-edwards** [comment]
We now have a "privacy" link in the footer that goes to the privacy policy at app/views/home/privacy.html.haml. It links to Virginia Tech's global terms of use and privacy policy. Those who fork the repo can create their own branch and override this policy statement with their own terms, if their site policy is different.
