### ISSUE TITLE
Cancan security controls need to be completed

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#2]
The implementation of the access controls on all the controllers needs to be completed.

**Comment by pmk1433** [comment]
Completed most of this after taking a disproportionately huge amount of time. Waiting to push to master and test it out on PROD.

**Comment by s-edwards** [comment]
Have you pushed this to master?  If so, I can deploy to production.

**Comment by pmk1433** [comment]
Needs to verified on PROD.

**Comment by pmk1433** [comment]
Need to look into this in 'student/instructor' mode on PROD to see if things are as they should be with the new abilities file.

**Comment by s-edwards** [comment]
From my quick interactive testing of it in development and production, it looks like things are working as expected.  There are still some controllers that need to be refactored to be cleaner and less repetitive, but I'm satisfied this issue is resolved to where it needs to be.  Try it on on the production site, then close this issue when you're ready.

**Comment by pmk1433** [comment]
I am still a bit skeptical whether all the permission checks that we might need are there. I will tentatively close this issue from what I have seen since the 'implementation' is more or less there. I will open another issue to remind ourselves that we need to do extensive permission validation before we ship this to our undergrads in this Summer.
