### ISSUE TITLE
Testing Exercise in C++

### ISSUE THREAD

**Issue by yurifeitosa** [web-cat/code-workout#213]
After upload an exercise (factorial example) in C++ on http://localhost:9292/gym/exercises/new and after put the aswer, the questions feedback don´t appear.

Have any extra configuration for Code-Workout works in C++?

Nothing happens when the answer is verified.

Thanks.
<img width="438" alt="2021-11-29 15_08_54-Ubuntu  Executando  - Oracle VM VirtualBox" src="https://user-images.githubusercontent.com/28274098/143920476-dc866359-6de6-4278-8cb9-f65f0cea8ee9.png">

**Comment by s-edwards** [comment]
C++ support requires docker to be installed. It sounds like you may not have docker set up, and so CodeWorkout is unable to run the sandboxing code to compile/execute the C++ answer.

**Comment by orcmid** [comment]
The README is written to imply that the docker setup is only needed for "development."  That's a lot of dependencies for someone who wants to learn C/C++ and is maybe a serious beginner, or who wants to see the exercises and maybe ask about them.

**Comment by s-edwards** [comment]
I agree ... but CodeWorkout was not intended for beginners to run local copies to learn C/C++. It's a fairly complex web application that requires a fair amount of non-beginner knowledge to set up and use. As such, it does have some serious environmental dependencies.

The comment in the readme is for using docker for a basic development environment, which is enough to do serious development work without having to install other dependencies, but is not enough to run a production web application that is full-featured. In particular, that docker environment probably won't run most languages other than Java, due to docker-in-docker issues.
