### ISSUE TITLE
Update the sidebar thumbnails during exercise practice

### ISSUE THREAD

**Issue by pmk1433** [web-cat/code-workout#54]
Get the sidebar scores for the current exercise and the workout thumbnail updated when exercise feedback comes in, as well as adding current exercise points with a radial progress bar to the feedback section on the right.

**Comment by s-edwards** [comment]
Added a quick fix for this, checked into master.  Slight modifications to sse/feedback_update.js.coffee now cause the entire sidebar to be re-rendered when new feedback is rendered, which causes both the workout thumbnail and the current exercise's thumbnail to be updated.  This is overkill, since it re-renders the whole sidebar instead of just the two thumbnails that need updating, but it was fast and is good enough until a more elegant fix comes along.

**Comment by pmk1433** [comment]
Closing it out. We can remove the 'overkill' mentioned above in a new issue.
