### ISSUE TITLE
Fix exercises_controller#random_exercise to use all ids

### ISSUE THREAD

**Issue by s-edwards** [web-cat/code-workout#7]
The exercises_controller#random_exercise method limits results to id numbers >= 200.  This is an artifact of the test database used during development, and should be fixed to use the full range of available exercises.  Also, double-check that it only pulls from public exercises.

**Comment by pmk1433** [comment]
Fixed on my side, waiting for push to PROD.

**Comment by s-edwards** [comment]
Commit and push to master, so I can deploy it for testing.

**Comment by pmk1433** [comment]
Looks like this is done but the thing is, in PROD database, a lot of the invalid/text exercises are present and thus is the random selection of exercises is throwing up an error page because it opening such pages. Probably need to clean up PROD database such that it does not contain any exercise with id <= 202 and should delete all their parent base_exercises.

**Comment by s-edwards** [comment]
Are these issues fixed in the development db snapshot on drobox?  If so, I can switch that one in.

**Comment by pmk1433** [comment]
I have made some further tweaks to my DEV db and put it on Dropbox. Please send it out PROD so that we can see whether things well from there.

**Comment by pmk1433** [comment]
Looks alright in PROD. What is your take on this?

**Comment by s-edwards** [comment]
Done.
