### ISSUE TITLE
Incorrect workout/exercise information in the sidebar.

### ISSUE THREAD

**Issue by ayaankazerouni** [web-cat/code-workout#99]
A link to the wrong workout appears in the sidebar, and the exercise thumbnails link to the wrong workout's exercises' practice pages. Should link to appropriate review pages.

**Comment by ayaankazerouni** [comment]
Ok, this is fixed. See the commits that reference this issue. @s-edwards, I'd appreciate a code review of this, especially of the change in *app/views/layouts/_two_columns_body.html.haml*. It seems a bit too tailored to the review scenario, but at the same time I can't think of a situation where this could break. Thanks!

**Comment by ayaankazerouni** [comment]
Update: current_workout_score should be changed to use the workout_score that is currently under review. Need to work on this further.

**Comment by ayaankazerouni** [comment]
I believe this is fixed now. The exercises#practice action was doing all the work figuring out the correct workout_score and putting it in an instance variable, but the sidebar view was simply using the current_workout relation. So it was just a matter of checking for the instance variable and using that, not much else.

Closing.

**Comment by ayaankazerouni** [comment]
There is incorrect information in the sidebar in other modes as well (working on an exercise in a workout offering as well as in practice mode).

**Comment by ayaankazerouni** [comment]
This is an old issue, so I expect we've talked about this before. But what exactly is the purpose of the `current_workout_score` association between the `users` and `workout_scores` tables? It's pretty prominent in any code I would need to modify to deal with this issue.

**Comment by s-edwards** [comment]
> But what exactly is the purpose of the current_workout_score association

It serves as a way to keep track of the current (or most recent) workout the user has been practicing, in order to populate the left sidebar with appropriate contents.  It was created to address numerous problems that existed prior to its creation, back when that information was pushed into the session instead of being stored in the database. It works OK currently, although it does need to be "reset" appropriately instead of carried around after it is no longer valid (causing inappropriate/stale sidebar contents in some circumstances).

I think the situations where "there is incorrect information in the sidebar" correspond to situations where this association should have been reset/cleared at some point, but wasn't.  The information in the sidebar is incorrect for the current context, but was correct for a previous context back when the association was valid.  I think the answer is to more actively maintain the state of this association, instead of treating it like a "set and forget" piece of state.  If you're not sure where it needs to be reset, we can go through the basics and plan out where to add the clears/resets.

**Comment by ayaankazerouni** [comment]
In `exercises#practice`, a `@workout_score` instance variable is defined, using the `current_workout_score` association, and I think this was the problem. I re-did that bit to define `@workout_score` independent of the association, and then set the association according to the instance variable.
Testing on the following scenarios showed the right information/urls:
* Practice an exercise in the gym
* Practice a workout in the gym
* Practice a workout_offering
* Review a workout_offering

Closing for now.
